api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            items_per_page: 20
            client_enabled: true #donner au client la possiblité de demander une pagination pendant la request
            client_items_per_page: true
            items_per_page_parameter_name: "count"
    formats:
        json:     ['application/json']
        jsonld:     ['application/json+ld']
        html: ['text/html']
        multipart: ['multipart/form-data']
